
server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: wms_route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms_route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums_route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: sms_route
          uri: lb:sms-service
          predicates:
            - Path=/sms/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ##namespace: 9c76dca1-9d93-4055-9401-8bbeb629596e
  application:
    name: geteway



