server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  rabbitmq:
      host: 127.0.0.1
      virtual-host: /liuhao
      password: liuhao
      username: liuhao
      port: 5672
